In [1]:
from pyspark.mllib.stat import Statistics
from pyspark.mllib.linalg import Vectors
import numpy as np
from datetime import datetime
from pyspark.sql.functions import udf, col
from pyspark.sql.types import DateType

In [2]:
sc

<SparkContext master=local[*] appName=PySparkShell>

In [3]:
key_id = 'AKIAJXBU2EK4HLF5SVHA'
access_key = 't03HUEi4mBGutI+pARJVYEyi+RZSBZXOpdLc3xLr'
region = "us-east-2"
sc.setSystemProperty("com.amazonaws.services.s3.enableV4",   "true")
sc._jsc.hadoopConfiguration().set("fs.s3a.awsAccessKeyId",   key_id)
sc._jsc.hadoopConfiguration().set("fs.s3a.awsSecretAccessKey",   access_key)
sc._jsc.hadoopConfiguration().set("fs.s3a.endpoint",   "s3."   +   region   +   ".amazonaws.com")

In [4]:
base_df = spark.read.option("header", "true").csv("s3a://ids-2017-group41-test/base_df_processed.csv", nanValue="")
# base_df1 = spark.read.option("header", "true").csv("s3a://ids-2017-group41-test/base_df_processed.csv", nanValue="")
# base_df = base_df.limit(10000)

In [5]:
base_df.printSchema()

root
 |-- date_time: string (nullable = true)
 |-- site_name: string (nullable = true)
 |-- posa_continent: string (nullable = true)
 |-- user_location_country: string (nullable = true)
 |-- user_location_region: string (nullable = true)
 |-- user_location_city: string (nullable = true)
 |-- orig_destination_distance: string (nullable = true)
 |-- user_id: string (nullable = true)
 |-- is_mobile: string (nullable = true)
 |-- is_package: string (nullable = true)
 |-- channel: string (nullable = true)
 |-- srch_ci: string (nullable = true)
 |-- srch_co: string (nullable = true)
 |-- srch_adults_cnt: string (nullable = true)
 |-- srch_children_cnt: string (nullable = true)
 |-- srch_rm_cnt: string (nullable = true)
 |-- srch_destination_id: string (nullable = true)
 |-- srch_destination_type_id: string (nullable = true)
 |-- is_booking: string (nullable = true)
 |-- cnt: string (nullable = true)
 |-- hotel_continent: string (nullable = true)
 |-- hotel_country: string (nullable = true)
 

In [6]:
names = base_df.schema.names
null_count = []
for col_x in names:
    null_count.append(base_df.where(col(col_x).isNull()).count())
    
print(null_count)

[0, 0, 0, 0, 0, 0, 3729, 0, 0, 0, 0, 7, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [7]:
base_df.take(1)

[Row(date_time='2014-08-11 07:46:59', site_name='2', posa_continent='3', user_location_country='66', user_location_region='348', user_location_city='48862', orig_destination_distance='2234.2641', user_id='12', is_mobile='0', is_package='1', channel='9', srch_ci='2014-08-27', srch_co='2014-08-31', srch_adults_cnt='2', srch_children_cnt='0', srch_rm_cnt='1', srch_destination_id='8250', srch_destination_type_id='1', is_booking='0', cnt='3', hotel_continent='2', hotel_country='50', hotel_market='628', hotel_cluster='1', BookingDate='2014-08-11', posa_continent1='3')]

In [8]:
# base_df = base_df.select('user_id', 'is_mobile', 'is_package', 'channel', 'srch_ci', 'srch_co', 'orig_destination_distance','srch_adults_cnt', 'srch_children_cnt', 'srch_destination_id', 'srch_destination_type_id','is_booking', 'cnt', 'hotel_continent', 'hotel_country', 'hotel_market', 'hotel_cluster')

In [9]:
base_df.take(1)

[Row(date_time='2014-08-11 07:46:59', site_name='2', posa_continent='3', user_location_country='66', user_location_region='348', user_location_city='48862', orig_destination_distance='2234.2641', user_id='12', is_mobile='0', is_package='1', channel='9', srch_ci='2014-08-27', srch_co='2014-08-31', srch_adults_cnt='2', srch_children_cnt='0', srch_rm_cnt='1', srch_destination_id='8250', srch_destination_type_id='1', is_booking='0', cnt='3', hotel_continent='2', hotel_country='50', hotel_market='628', hotel_cluster='1', BookingDate='2014-08-11', posa_continent1='3')]

In [10]:
# total no. of columns in new base_df.
len(base_df.schema.names)

26

In [11]:
# new base_df schema.
base_df.printSchema()

root
 |-- date_time: string (nullable = true)
 |-- site_name: string (nullable = true)
 |-- posa_continent: string (nullable = true)
 |-- user_location_country: string (nullable = true)
 |-- user_location_region: string (nullable = true)
 |-- user_location_city: string (nullable = true)
 |-- orig_destination_distance: string (nullable = true)
 |-- user_id: string (nullable = true)
 |-- is_mobile: string (nullable = true)
 |-- is_package: string (nullable = true)
 |-- channel: string (nullable = true)
 |-- srch_ci: string (nullable = true)
 |-- srch_co: string (nullable = true)
 |-- srch_adults_cnt: string (nullable = true)
 |-- srch_children_cnt: string (nullable = true)
 |-- srch_rm_cnt: string (nullable = true)
 |-- srch_destination_id: string (nullable = true)
 |-- srch_destination_type_id: string (nullable = true)
 |-- is_booking: string (nullable = true)
 |-- cnt: string (nullable = true)
 |-- hotel_continent: string (nullable = true)
 |-- hotel_country: string (nullable = true)
 

In [12]:
# filtering out columns where dates are null
base_df = base_df.where(col('srch_ci').isNotNull())
base_df = base_df.where(col('srch_co').isNotNull())
base_df.take(1)

[Row(date_time='2014-08-11 07:46:59', site_name='2', posa_continent='3', user_location_country='66', user_location_region='348', user_location_city='48862', orig_destination_distance='2234.2641', user_id='12', is_mobile='0', is_package='1', channel='9', srch_ci='2014-08-27', srch_co='2014-08-31', srch_adults_cnt='2', srch_children_cnt='0', srch_rm_cnt='1', srch_destination_id='8250', srch_destination_type_id='1', is_booking='0', cnt='3', hotel_continent='2', hotel_country='50', hotel_market='628', hotel_cluster='1', BookingDate='2014-08-11', posa_continent1='3')]

## converting srch_ci, srch_co to dates type

In [13]:
conv_to_date = udf(lambda x: datetime.strptime(x, '%Y-%m-%d'), DateType())

base_df = base_df.withColumn("srch_ci", conv_to_date(col('srch_ci')))
base_df = base_df.withColumn("srch_co", conv_to_date(col('srch_co')))

In [14]:
base_df.take(1)

[Row(date_time='2014-08-11 07:46:59', site_name='2', posa_continent='3', user_location_country='66', user_location_region='348', user_location_city='48862', orig_destination_distance='2234.2641', user_id='12', is_mobile='0', is_package='1', channel='9', srch_ci=datetime.date(2014, 8, 27), srch_co=datetime.date(2014, 8, 31), srch_adults_cnt='2', srch_children_cnt='0', srch_rm_cnt='1', srch_destination_id='8250', srch_destination_type_id='1', is_booking='0', cnt='3', hotel_continent='2', hotel_country='50', hotel_market='628', hotel_cluster='1', BookingDate='2014-08-11', posa_continent1='3')]

In [15]:
base_df.printSchema()

root
 |-- date_time: string (nullable = true)
 |-- site_name: string (nullable = true)
 |-- posa_continent: string (nullable = true)
 |-- user_location_country: string (nullable = true)
 |-- user_location_region: string (nullable = true)
 |-- user_location_city: string (nullable = true)
 |-- orig_destination_distance: string (nullable = true)
 |-- user_id: string (nullable = true)
 |-- is_mobile: string (nullable = true)
 |-- is_package: string (nullable = true)
 |-- channel: string (nullable = true)
 |-- srch_ci: date (nullable = true)
 |-- srch_co: date (nullable = true)
 |-- srch_adults_cnt: string (nullable = true)
 |-- srch_children_cnt: string (nullable = true)
 |-- srch_rm_cnt: string (nullable = true)
 |-- srch_destination_id: string (nullable = true)
 |-- srch_destination_type_id: string (nullable = true)
 |-- is_booking: string (nullable = true)
 |-- cnt: string (nullable = true)
 |-- hotel_continent: string (nullable = true)
 |-- hotel_country: string (nullable = true)
 |-- 

## changing the type of datetime to date

In [16]:
conv_to_date2 = udf(lambda x: datetime.strptime(x[:10], '%Y-%m-%d'), DateType())
base_df = base_df.withColumn("booking_date", conv_to_date2(col('date_time')))

In [17]:
base_df.take(1)

[Row(date_time='2014-08-11 07:46:59', site_name='2', posa_continent='3', user_location_country='66', user_location_region='348', user_location_city='48862', orig_destination_distance='2234.2641', user_id='12', is_mobile='0', is_package='1', channel='9', srch_ci=datetime.date(2014, 8, 27), srch_co=datetime.date(2014, 8, 31), srch_adults_cnt='2', srch_children_cnt='0', srch_rm_cnt='1', srch_destination_id='8250', srch_destination_type_id='1', is_booking='0', cnt='3', hotel_continent='2', hotel_country='50', hotel_market='628', hotel_cluster='1', BookingDate='2014-08-11', posa_continent1='3', booking_date=datetime.date(2014, 8, 11))]

In [18]:
base_df.printSchema()

root
 |-- date_time: string (nullable = true)
 |-- site_name: string (nullable = true)
 |-- posa_continent: string (nullable = true)
 |-- user_location_country: string (nullable = true)
 |-- user_location_region: string (nullable = true)
 |-- user_location_city: string (nullable = true)
 |-- orig_destination_distance: string (nullable = true)
 |-- user_id: string (nullable = true)
 |-- is_mobile: string (nullable = true)
 |-- is_package: string (nullable = true)
 |-- channel: string (nullable = true)
 |-- srch_ci: date (nullable = true)
 |-- srch_co: date (nullable = true)
 |-- srch_adults_cnt: string (nullable = true)
 |-- srch_children_cnt: string (nullable = true)
 |-- srch_rm_cnt: string (nullable = true)
 |-- srch_destination_id: string (nullable = true)
 |-- srch_destination_type_id: string (nullable = true)
 |-- is_booking: string (nullable = true)
 |-- cnt: string (nullable = true)
 |-- hotel_continent: string (nullable = true)
 |-- hotel_country: string (nullable = true)
 |-- 

In [19]:
names_df = base_df.schema.names
names_df.remove('date_time')
names_df.remove('posa_continent1')
names_df.remove('BookingDate')
base_df = base_df.select(*names_df)

In [20]:
base_df.take(1)

[Row(site_name='2', posa_continent='3', user_location_country='66', user_location_region='348', user_location_city='48862', orig_destination_distance='2234.2641', user_id='12', is_mobile='0', is_package='1', channel='9', srch_ci=datetime.date(2014, 8, 27), srch_co=datetime.date(2014, 8, 31), srch_adults_cnt='2', srch_children_cnt='0', srch_rm_cnt='1', srch_destination_id='8250', srch_destination_type_id='1', is_booking='0', cnt='3', hotel_continent='2', hotel_country='50', hotel_market='628', hotel_cluster='1', booking_date=datetime.date(2014, 8, 11))]

In [21]:
base_df.printSchema()

root
 |-- site_name: string (nullable = true)
 |-- posa_continent: string (nullable = true)
 |-- user_location_country: string (nullable = true)
 |-- user_location_region: string (nullable = true)
 |-- user_location_city: string (nullable = true)
 |-- orig_destination_distance: string (nullable = true)
 |-- user_id: string (nullable = true)
 |-- is_mobile: string (nullable = true)
 |-- is_package: string (nullable = true)
 |-- channel: string (nullable = true)
 |-- srch_ci: date (nullable = true)
 |-- srch_co: date (nullable = true)
 |-- srch_adults_cnt: string (nullable = true)
 |-- srch_children_cnt: string (nullable = true)
 |-- srch_rm_cnt: string (nullable = true)
 |-- srch_destination_id: string (nullable = true)
 |-- srch_destination_type_id: string (nullable = true)
 |-- is_booking: string (nullable = true)
 |-- cnt: string (nullable = true)
 |-- hotel_continent: string (nullable = true)
 |-- hotel_country: string (nullable = true)
 |-- hotel_market: string (nullable = true)
 |

## converting all remaining data types to int.

In [22]:
col_names = base_df.schema.names

col_names.remove('srch_ci')
col_names.remove('srch_co')
col_names.remove('booking_date')

for names in col_names:
    base_df = base_df.withColumn(names, base_df[names].cast("int"))
    
base_df.printSchema()

root
 |-- site_name: integer (nullable = true)
 |-- posa_continent: integer (nullable = true)
 |-- user_location_country: integer (nullable = true)
 |-- user_location_region: integer (nullable = true)
 |-- user_location_city: integer (nullable = true)
 |-- orig_destination_distance: integer (nullable = true)
 |-- user_id: integer (nullable = true)
 |-- is_mobile: integer (nullable = true)
 |-- is_package: integer (nullable = true)
 |-- channel: integer (nullable = true)
 |-- srch_ci: date (nullable = true)
 |-- srch_co: date (nullable = true)
 |-- srch_adults_cnt: integer (nullable = true)
 |-- srch_children_cnt: integer (nullable = true)
 |-- srch_rm_cnt: integer (nullable = true)
 |-- srch_destination_id: integer (nullable = true)
 |-- srch_destination_type_id: integer (nullable = true)
 |-- is_booking: integer (nullable = true)
 |-- cnt: integer (nullable = true)
 |-- hotel_continent: integer (nullable = true)
 |-- hotel_country: integer (nullable = true)
 |-- hotel_market: integer 

In [23]:
base_df.take(1)

[Row(site_name=2, posa_continent=3, user_location_country=66, user_location_region=348, user_location_city=48862, orig_destination_distance=2234, user_id=12, is_mobile=0, is_package=1, channel=9, srch_ci=datetime.date(2014, 8, 27), srch_co=datetime.date(2014, 8, 31), srch_adults_cnt=2, srch_children_cnt=0, srch_rm_cnt=1, srch_destination_id=8250, srch_destination_type_id=1, is_booking=0, cnt=3, hotel_continent=2, hotel_country=50, hotel_market=628, hotel_cluster=1, booking_date=datetime.date(2014, 8, 11))]

## Scaling all numerical data types.

In [24]:
from pyspark.ml.feature import VectorAssembler
from pyspark.ml.feature import MinMaxScaler
from pyspark.ml.linalg import Vectors

In [25]:
col_names.remove('orig_destination_distance')

In [26]:
def scaleColumns(base_df, col_name):
    # creating vector for column.
    col_feature = col_name + "_feature"
    assembler = VectorAssembler(
            inputCols=[col_name],
            outputCol=col_feature)
    assembled = assembler.transform(base_df)
    
    col_scaled = col_name + "_scaled"
    # creating scaled rows for the column.
    scaler = MinMaxScaler(inputCol=col_feature, outputCol=col_scaled)
    scalerModel = scaler.fit(assembled)
    base_df = scalerModel.transform(assembled)
    return base_df

In [27]:
for col_name in col_names:
    base_df = scaleColumns(base_df, col_name)
    
base_df.printSchema()

root
 |-- site_name: integer (nullable = true)
 |-- posa_continent: integer (nullable = true)
 |-- user_location_country: integer (nullable = true)
 |-- user_location_region: integer (nullable = true)
 |-- user_location_city: integer (nullable = true)
 |-- orig_destination_distance: integer (nullable = true)
 |-- user_id: integer (nullable = true)
 |-- is_mobile: integer (nullable = true)
 |-- is_package: integer (nullable = true)
 |-- channel: integer (nullable = true)
 |-- srch_ci: date (nullable = true)
 |-- srch_co: date (nullable = true)
 |-- srch_adults_cnt: integer (nullable = true)
 |-- srch_children_cnt: integer (nullable = true)
 |-- srch_rm_cnt: integer (nullable = true)
 |-- srch_destination_id: integer (nullable = true)
 |-- srch_destination_type_id: integer (nullable = true)
 |-- is_booking: integer (nullable = true)
 |-- cnt: integer (nullable = true)
 |-- hotel_continent: integer (nullable = true)
 |-- hotel_country: integer (nullable = true)
 |-- hotel_market: integer 

In [28]:
base_df.take(1)

[Row(site_name=2, posa_continent=3, user_location_country=66, user_location_region=348, user_location_city=48862, orig_destination_distance=2234, user_id=12, is_mobile=0, is_package=1, channel=9, srch_ci=datetime.date(2014, 8, 27), srch_co=datetime.date(2014, 8, 31), srch_adults_cnt=2, srch_children_cnt=0, srch_rm_cnt=1, srch_destination_id=8250, srch_destination_type_id=1, is_booking=0, cnt=3, hotel_continent=2, hotel_country=50, hotel_market=628, hotel_cluster=1, booking_date=datetime.date(2014, 8, 11), site_name_feature=DenseVector([2.0]), site_name_scaled=DenseVector([0.0]), posa_continent_feature=DenseVector([3.0]), posa_continent_scaled=DenseVector([0.75]), user_location_country_feature=DenseVector([66.0]), user_location_country_scaled=DenseVector([0.2762]), user_location_region_feature=DenseVector([348.0]), user_location_region_scaled=DenseVector([0.347]), user_location_city_feature=DenseVector([48862.0]), user_location_city_scaled=DenseVector([0.8656]), user_id_feature=DenseVec

## Adding Season column for applying filtering.

In [29]:
from pyspark.sql import functions as F

def returnSeason(x):
    if x in [1, 2, 12]:
        return "0"
    elif x in [3, 4, 5]:
        return "1"
    elif x in [6, 7, 8]:
        return "2"
    elif x in [9, 10, 11]:
        return "3"
    
season_udf = udf(returnSeason, "int")

In [30]:
base_df = base_df.withColumn('travel_season', season_udf(F.month(col('srch_ci'))))

In [31]:
base_df.printSchema()

root
 |-- site_name: integer (nullable = true)
 |-- posa_continent: integer (nullable = true)
 |-- user_location_country: integer (nullable = true)
 |-- user_location_region: integer (nullable = true)
 |-- user_location_city: integer (nullable = true)
 |-- orig_destination_distance: integer (nullable = true)
 |-- user_id: integer (nullable = true)
 |-- is_mobile: integer (nullable = true)
 |-- is_package: integer (nullable = true)
 |-- channel: integer (nullable = true)
 |-- srch_ci: date (nullable = true)
 |-- srch_co: date (nullable = true)
 |-- srch_adults_cnt: integer (nullable = true)
 |-- srch_children_cnt: integer (nullable = true)
 |-- srch_rm_cnt: integer (nullable = true)
 |-- srch_destination_id: integer (nullable = true)
 |-- srch_destination_type_id: integer (nullable = true)
 |-- is_booking: integer (nullable = true)
 |-- cnt: integer (nullable = true)
 |-- hotel_continent: integer (nullable = true)
 |-- hotel_country: integer (nullable = true)
 |-- hotel_market: integer 

In [32]:
base_df.take(1)

[Row(site_name=2, posa_continent=3, user_location_country=66, user_location_region=348, user_location_city=48862, orig_destination_distance=2234, user_id=12, is_mobile=0, is_package=1, channel=9, srch_ci=datetime.date(2014, 8, 27), srch_co=datetime.date(2014, 8, 31), srch_adults_cnt=2, srch_children_cnt=0, srch_rm_cnt=1, srch_destination_id=8250, srch_destination_type_id=1, is_booking=0, cnt=3, hotel_continent=2, hotel_country=50, hotel_market=628, hotel_cluster=1, booking_date=datetime.date(2014, 8, 11), site_name_feature=DenseVector([2.0]), site_name_scaled=DenseVector([0.0]), posa_continent_feature=DenseVector([3.0]), posa_continent_scaled=DenseVector([0.75]), user_location_country_feature=DenseVector([66.0]), user_location_country_scaled=DenseVector([0.2762]), user_location_region_feature=DenseVector([348.0]), user_location_region_scaled=DenseVector([0.347]), user_location_city_feature=DenseVector([48862.0]), user_location_city_scaled=DenseVector([0.8656]), user_id_feature=DenseVec

## adding column to total the number of people in the booking.

In [33]:
def addPeople(x1, x2):
    return x1+x2

udf_people = udf(addPeople, "int")

In [34]:
base_df = base_df.withColumn("no_persons", udf_people(col('srch_adults_cnt'), col('srch_children_cnt')))

In [35]:
base_df.take(1)

[Row(site_name=2, posa_continent=3, user_location_country=66, user_location_region=348, user_location_city=48862, orig_destination_distance=2234, user_id=12, is_mobile=0, is_package=1, channel=9, srch_ci=datetime.date(2014, 8, 27), srch_co=datetime.date(2014, 8, 31), srch_adults_cnt=2, srch_children_cnt=0, srch_rm_cnt=1, srch_destination_id=8250, srch_destination_type_id=1, is_booking=0, cnt=3, hotel_continent=2, hotel_country=50, hotel_market=628, hotel_cluster=1, booking_date=datetime.date(2014, 8, 11), site_name_feature=DenseVector([2.0]), site_name_scaled=DenseVector([0.0]), posa_continent_feature=DenseVector([3.0]), posa_continent_scaled=DenseVector([0.75]), user_location_country_feature=DenseVector([66.0]), user_location_country_scaled=DenseVector([0.2762]), user_location_region_feature=DenseVector([348.0]), user_location_region_scaled=DenseVector([0.347]), user_location_city_feature=DenseVector([48862.0]), user_location_city_scaled=DenseVector([0.8656]), user_id_feature=DenseVec

In [36]:
# scaling no_persons.
base_df = scaleColumns(base_df, 'no_persons')
base_df.printSchema()

root
 |-- site_name: integer (nullable = true)
 |-- posa_continent: integer (nullable = true)
 |-- user_location_country: integer (nullable = true)
 |-- user_location_region: integer (nullable = true)
 |-- user_location_city: integer (nullable = true)
 |-- orig_destination_distance: integer (nullable = true)
 |-- user_id: integer (nullable = true)
 |-- is_mobile: integer (nullable = true)
 |-- is_package: integer (nullable = true)
 |-- channel: integer (nullable = true)
 |-- srch_ci: date (nullable = true)
 |-- srch_co: date (nullable = true)
 |-- srch_adults_cnt: integer (nullable = true)
 |-- srch_children_cnt: integer (nullable = true)
 |-- srch_rm_cnt: integer (nullable = true)
 |-- srch_destination_id: integer (nullable = true)
 |-- srch_destination_type_id: integer (nullable = true)
 |-- is_booking: integer (nullable = true)
 |-- cnt: integer (nullable = true)
 |-- hotel_continent: integer (nullable = true)
 |-- hotel_country: integer (nullable = true)
 |-- hotel_market: integer 

In [37]:
base_df.take(1)

[Row(site_name=2, posa_continent=3, user_location_country=66, user_location_region=348, user_location_city=48862, orig_destination_distance=2234, user_id=12, is_mobile=0, is_package=1, channel=9, srch_ci=datetime.date(2014, 8, 27), srch_co=datetime.date(2014, 8, 31), srch_adults_cnt=2, srch_children_cnt=0, srch_rm_cnt=1, srch_destination_id=8250, srch_destination_type_id=1, is_booking=0, cnt=3, hotel_continent=2, hotel_country=50, hotel_market=628, hotel_cluster=1, booking_date=datetime.date(2014, 8, 11), site_name_feature=DenseVector([2.0]), site_name_scaled=DenseVector([0.0]), posa_continent_feature=DenseVector([3.0]), posa_continent_scaled=DenseVector([0.75]), user_location_country_feature=DenseVector([66.0]), user_location_country_scaled=DenseVector([0.2762]), user_location_region_feature=DenseVector([348.0]), user_location_region_scaled=DenseVector([0.347]), user_location_city_feature=DenseVector([48862.0]), user_location_city_scaled=DenseVector([0.8656]), user_id_feature=DenseVec

## calculating the number of days, guests stayed at the hotel

In [38]:
base_df = base_df.withColumn("days_stayed", F.datediff(col('srch_co'), col('srch_ci')))

In [39]:
base_df.printSchema()

root
 |-- site_name: integer (nullable = true)
 |-- posa_continent: integer (nullable = true)
 |-- user_location_country: integer (nullable = true)
 |-- user_location_region: integer (nullable = true)
 |-- user_location_city: integer (nullable = true)
 |-- orig_destination_distance: integer (nullable = true)
 |-- user_id: integer (nullable = true)
 |-- is_mobile: integer (nullable = true)
 |-- is_package: integer (nullable = true)
 |-- channel: integer (nullable = true)
 |-- srch_ci: date (nullable = true)
 |-- srch_co: date (nullable = true)
 |-- srch_adults_cnt: integer (nullable = true)
 |-- srch_children_cnt: integer (nullable = true)
 |-- srch_rm_cnt: integer (nullable = true)
 |-- srch_destination_id: integer (nullable = true)
 |-- srch_destination_type_id: integer (nullable = true)
 |-- is_booking: integer (nullable = true)
 |-- cnt: integer (nullable = true)
 |-- hotel_continent: integer (nullable = true)
 |-- hotel_country: integer (nullable = true)
 |-- hotel_market: integer 

In [40]:
base_df.take(1)

[Row(site_name=2, posa_continent=3, user_location_country=66, user_location_region=348, user_location_city=48862, orig_destination_distance=2234, user_id=12, is_mobile=0, is_package=1, channel=9, srch_ci=datetime.date(2014, 8, 27), srch_co=datetime.date(2014, 8, 31), srch_adults_cnt=2, srch_children_cnt=0, srch_rm_cnt=1, srch_destination_id=8250, srch_destination_type_id=1, is_booking=0, cnt=3, hotel_continent=2, hotel_country=50, hotel_market=628, hotel_cluster=1, booking_date=datetime.date(2014, 8, 11), site_name_feature=DenseVector([2.0]), site_name_scaled=DenseVector([0.0]), posa_continent_feature=DenseVector([3.0]), posa_continent_scaled=DenseVector([0.75]), user_location_country_feature=DenseVector([66.0]), user_location_country_scaled=DenseVector([0.2762]), user_location_region_feature=DenseVector([348.0]), user_location_region_scaled=DenseVector([0.347]), user_location_city_feature=DenseVector([48862.0]), user_location_city_scaled=DenseVector([0.8656]), user_id_feature=DenseVec

## Calculating the distance values for the origin_distance.

In [41]:
base_df.printSchema()

root
 |-- site_name: integer (nullable = true)
 |-- posa_continent: integer (nullable = true)
 |-- user_location_country: integer (nullable = true)
 |-- user_location_region: integer (nullable = true)
 |-- user_location_city: integer (nullable = true)
 |-- orig_destination_distance: integer (nullable = true)
 |-- user_id: integer (nullable = true)
 |-- is_mobile: integer (nullable = true)
 |-- is_package: integer (nullable = true)
 |-- channel: integer (nullable = true)
 |-- srch_ci: date (nullable = true)
 |-- srch_co: date (nullable = true)
 |-- srch_adults_cnt: integer (nullable = true)
 |-- srch_children_cnt: integer (nullable = true)
 |-- srch_rm_cnt: integer (nullable = true)
 |-- srch_destination_id: integer (nullable = true)
 |-- srch_destination_type_id: integer (nullable = true)
 |-- is_booking: integer (nullable = true)
 |-- cnt: integer (nullable = true)
 |-- hotel_continent: integer (nullable = true)
 |-- hotel_country: integer (nullable = true)
 |-- hotel_market: integer 

In [42]:
# regression_df = base_df1.select('orig_destination_distance','posa_continent','user_location_country','user_location_region','user_location_city', 'hotel_continent', 'hotel_country', 'hotel_market')

In [43]:
# regression_df.printSchema()

In [44]:
# regression_df.take(1)

In [45]:
# regression_df = regression_df.where(col('orig_destination_distance').isNotNull())

In [46]:
# regression_df.take(1)

In [47]:
# reg_col_names = regression_df.schema.names
# # names.remove('user_id')

# for names in reg_col_names:
#     regression_df = regression_df.withColumn(names, regression_df[names].cast("int"))

In [48]:
# reg_col_names.remove('orig_destination_distance')

# for name in reg_col_names:
#     regression_df = scaleColumns(regression_df, name)

In [49]:
# regression_df.take(1)

In [50]:
# regression_df.printSchema()

In [51]:
regression_assembler = VectorAssembler(inputCols=['posa_continent_scaled', 'user_location_country_scaled', 'user_location_region_scaled', 'user_location_city_scaled', 'hotel_continent_scaled', 'hotel_country_scaled', 'hotel_market_scaled'],
                                      outputCol='features')

In [52]:
base_df = regression_assembler.transform(base_df)

In [53]:
base_df.take(1)

[Row(site_name=2, posa_continent=3, user_location_country=66, user_location_region=348, user_location_city=48862, orig_destination_distance=2234, user_id=12, is_mobile=0, is_package=1, channel=9, srch_ci=datetime.date(2014, 8, 27), srch_co=datetime.date(2014, 8, 31), srch_adults_cnt=2, srch_children_cnt=0, srch_rm_cnt=1, srch_destination_id=8250, srch_destination_type_id=1, is_booking=0, cnt=3, hotel_continent=2, hotel_country=50, hotel_market=628, hotel_cluster=1, booking_date=datetime.date(2014, 8, 11), site_name_feature=DenseVector([2.0]), site_name_scaled=DenseVector([0.0]), posa_continent_feature=DenseVector([3.0]), posa_continent_scaled=DenseVector([0.75]), user_location_country_feature=DenseVector([66.0]), user_location_country_scaled=DenseVector([0.2762]), user_location_region_feature=DenseVector([348.0]), user_location_region_scaled=DenseVector([0.347]), user_location_city_feature=DenseVector([48862.0]), user_location_city_scaled=DenseVector([0.8656]), user_id_feature=DenseVec

In [54]:
base_df.printSchema()

root
 |-- site_name: integer (nullable = true)
 |-- posa_continent: integer (nullable = true)
 |-- user_location_country: integer (nullable = true)
 |-- user_location_region: integer (nullable = true)
 |-- user_location_city: integer (nullable = true)
 |-- orig_destination_distance: integer (nullable = true)
 |-- user_id: integer (nullable = true)
 |-- is_mobile: integer (nullable = true)
 |-- is_package: integer (nullable = true)
 |-- channel: integer (nullable = true)
 |-- srch_ci: date (nullable = true)
 |-- srch_co: date (nullable = true)
 |-- srch_adults_cnt: integer (nullable = true)
 |-- srch_children_cnt: integer (nullable = true)
 |-- srch_rm_cnt: integer (nullable = true)
 |-- srch_destination_id: integer (nullable = true)
 |-- srch_destination_type_id: integer (nullable = true)
 |-- is_booking: integer (nullable = true)
 |-- cnt: integer (nullable = true)
 |-- hotel_continent: integer (nullable = true)
 |-- hotel_country: integer (nullable = true)
 |-- hotel_market: integer 

In [55]:
# regression_df = regression_df.select('orig_destination_distance', 'posa_continent_scaled','user_location_country_scaled', 'user_location_region_scaled', 'user_location_city_scaled', 'hotel_continent_scaled', 'hotel_country_scaled', 'hotel_market_scaled')

In [56]:
# regression_df.take(1)

In [57]:
# regression_df.printSchema()

In [58]:
# regression_assembled_rdd = regression_df.rdd
# regression_assembled_rdd.take(1)

In [59]:
regression_df = base_df.where(base_df['orig_destination_distance'].isNotNull())

In [60]:
regression_df.take(1)

[Row(site_name=2, posa_continent=3, user_location_country=66, user_location_region=348, user_location_city=48862, orig_destination_distance=2234, user_id=12, is_mobile=0, is_package=1, channel=9, srch_ci=datetime.date(2014, 8, 27), srch_co=datetime.date(2014, 8, 31), srch_adults_cnt=2, srch_children_cnt=0, srch_rm_cnt=1, srch_destination_id=8250, srch_destination_type_id=1, is_booking=0, cnt=3, hotel_continent=2, hotel_country=50, hotel_market=628, hotel_cluster=1, booking_date=datetime.date(2014, 8, 11), site_name_feature=DenseVector([2.0]), site_name_scaled=DenseVector([0.0]), posa_continent_feature=DenseVector([3.0]), posa_continent_scaled=DenseVector([0.75]), user_location_country_feature=DenseVector([66.0]), user_location_country_scaled=DenseVector([0.2762]), user_location_region_feature=DenseVector([348.0]), user_location_region_scaled=DenseVector([0.347]), user_location_city_feature=DenseVector([48862.0]), user_location_city_scaled=DenseVector([0.8656]), user_id_feature=DenseVec

In [61]:
from pyspark.ml.regression import LinearRegression
lr = LinearRegression(featuresCol="features", labelCol="orig_destination_distance", regParam=100.0, maxIter=10, predictionCol="predicted_distance")

In [62]:
rmodel = lr.fit(regression_df)

In [63]:
rmodel.numFeatures

7

In [64]:
base_df = rmodel.transform(base_df)

In [65]:
trainingSummary = rmodel.summary
trainingSummary.rootMeanSquaredError

1795.125907664273

In [66]:
base_df.take(1)

[Row(site_name=2, posa_continent=3, user_location_country=66, user_location_region=348, user_location_city=48862, orig_destination_distance=2234, user_id=12, is_mobile=0, is_package=1, channel=9, srch_ci=datetime.date(2014, 8, 27), srch_co=datetime.date(2014, 8, 31), srch_adults_cnt=2, srch_children_cnt=0, srch_rm_cnt=1, srch_destination_id=8250, srch_destination_type_id=1, is_booking=0, cnt=3, hotel_continent=2, hotel_country=50, hotel_market=628, hotel_cluster=1, booking_date=datetime.date(2014, 8, 11), site_name_feature=DenseVector([2.0]), site_name_scaled=DenseVector([0.0]), posa_continent_feature=DenseVector([3.0]), posa_continent_scaled=DenseVector([0.75]), user_location_country_feature=DenseVector([66.0]), user_location_country_scaled=DenseVector([0.2762]), user_location_region_feature=DenseVector([348.0]), user_location_region_scaled=DenseVector([0.347]), user_location_city_feature=DenseVector([48862.0]), user_location_city_scaled=DenseVector([0.8656]), user_id_feature=DenseVec

In [67]:
# def subRow(x, y):
#     if y is None:
#         return x
#     if x > y:
#         return x - 700
#     else:
#         return x + 700

# udf_row = udf(subRow)

In [68]:
# base_df1 = base_df.withColumn('predicted_distance', udf_row(col('predicted_distance'), col('orig_destination_distance')))

In [69]:
# base_df1.take(10)

In [70]:
# base_df1 = base_df1.withColumn('predicted_distance', base_df1['predicted_distance'].cast("double"))
# from pyspark.ml.evaluation import RegressionEvaluator
# evaluator = RegressionEvaluator(metricName="rmse", labelCol="orig_destination_distance", predictionCol="predicted_distance")

# RMSE = evaluator.evaluate(base_df1)

In [71]:
row5_df_assembler = VectorAssembler(
        inputCols=['posa_continent_scaled','site_name_scaled','user_location_country_scaled','user_location_region_scaled','user_location_city_scaled'],
        outputCol="kmeans_features")

base_df = row5_df_assembler.transform(base_df)

In [72]:
# feature_df=fbase_df.select('user_id','site_name','posa_continent','user_location_country','user_location_region','user_location_city','features1')

In [73]:
base_df.printSchema()

root
 |-- site_name: integer (nullable = true)
 |-- posa_continent: integer (nullable = true)
 |-- user_location_country: integer (nullable = true)
 |-- user_location_region: integer (nullable = true)
 |-- user_location_city: integer (nullable = true)
 |-- orig_destination_distance: integer (nullable = true)
 |-- user_id: integer (nullable = true)
 |-- is_mobile: integer (nullable = true)
 |-- is_package: integer (nullable = true)
 |-- channel: integer (nullable = true)
 |-- srch_ci: date (nullable = true)
 |-- srch_co: date (nullable = true)
 |-- srch_adults_cnt: integer (nullable = true)
 |-- srch_children_cnt: integer (nullable = true)
 |-- srch_rm_cnt: integer (nullable = true)
 |-- srch_destination_id: integer (nullable = true)
 |-- srch_destination_type_id: integer (nullable = true)
 |-- is_booking: integer (nullable = true)
 |-- cnt: integer (nullable = true)
 |-- hotel_continent: integer (nullable = true)
 |-- hotel_country: integer (nullable = true)
 |-- hotel_market: integer 

In [74]:
# feature_df = feature_df.withColumn("features", col("features1"))

In [75]:
base_df.take(1)

[Row(site_name=2, posa_continent=3, user_location_country=66, user_location_region=348, user_location_city=48862, orig_destination_distance=2234, user_id=12, is_mobile=0, is_package=1, channel=9, srch_ci=datetime.date(2014, 8, 27), srch_co=datetime.date(2014, 8, 31), srch_adults_cnt=2, srch_children_cnt=0, srch_rm_cnt=1, srch_destination_id=8250, srch_destination_type_id=1, is_booking=0, cnt=3, hotel_continent=2, hotel_country=50, hotel_market=628, hotel_cluster=1, booking_date=datetime.date(2014, 8, 11), site_name_feature=DenseVector([2.0]), site_name_scaled=DenseVector([0.0]), posa_continent_feature=DenseVector([3.0]), posa_continent_scaled=DenseVector([0.75]), user_location_country_feature=DenseVector([66.0]), user_location_country_scaled=DenseVector([0.2762]), user_location_region_feature=DenseVector([348.0]), user_location_region_scaled=DenseVector([0.347]), user_location_city_feature=DenseVector([48862.0]), user_location_city_scaled=DenseVector([0.8656]), user_id_feature=DenseVec

In [76]:
# feature_df=fbase_df.select('user_id','site_name','posa_continent','user_location_country','user_location_region','user_location_city','features')

In [77]:
# feature_df.take(1)

In [78]:
from pyspark.ml.clustering import KMeans

In [79]:
kmeans = KMeans(featuresCol="kmeans_features", predictionCol="predicted_clusters", k=100,initMode="k-means||", initSteps=2, tol=1e-4,maxIter=20,seed=7)
# kmeans = KMeans().setK(150).setSeed(7)
# kmodel = kmeans.fit(feature_df)
# wssse = kmodel.computeCost(feature_df)

# print(wssse)

In [80]:
kmodel = kmeans.fit(base_df)

In [81]:
centers = kmodel.clusterCenters()
print("Cluster Centers: ")
for center in centers:
    print(center)

Cluster Centers: 
[ 0.75        0.          0.27615063  0.44914901  0.75690952]
[ 0.75        0.19393939  0.85368328  0.3589761   0.44209205]
[ 0.75        0.71111111  0.0125523   0.06281157  0.02138251]
[ 0.75        0.          0.27571643  0.34377998  0.03378915]
[ 0.75        0.          0.97966437  0.02496811  0.94949258]
[ 0.375       0.76984127  0.36820084  0.13317191  0.86813907]
[ 0.75        0.          0.72384937  0.84546361  0.48208971]
[ 0.5         0.71490515  0.29288703  0.06504876  0.19075056]
[ 0.75        0.          0.26926711  0.16036836  0.40705262]
[ 0.75        0.00212766  0.27615063  0.31692158  0.9438261 ]
[ 0.75        0.          1.          0.35792622  0.17490434]
[ 0.5         0.51111111  0.09623431  0.04785643  0.08717758]
[ 0.5         0.67641326  0.83491155  0.0434486   0.75375349]
[ 0.75        0.          0.27485555  0.35794759  0.47079731]
[ 0.75        0.          0.27615063  0.16605163  0.11277835]
[ 0.          0.17777778  0.76150628  0.19840479  0.

In [82]:
kmodel.computeCost(base_df)

30.845253847040986

In [ ]:
base_df = kmodel.transform(base_df)

In [ ]:
base_df.take(1)

In [ ]:
base_df.printSchema()

## need to convert ml.Vectors to mllib.Vector for using matrix factorization models.

In [ ]:
type(base_df)

In [103]:
new_df = base_df.select('predicted_clusters', 'hotel_cluster', 'predicted_distance')

In [104]:
new_df = new_df.take(1)

In [ ]:
new_df.printSchema()

In [ ]:
base_rdd = new_df.rdd

In [94]:
base_rdd.take(1)

KeyboardInterrupt: 

In [ ]:
ratings = base_rdd.map(lambda x: x[0], x[1], x[2])

In [79]:
from pyspark.mllib.recommendation import ALS, MatrixFactorizationModel, Rating
rank = 10
numIterations = 10

In [ ]:
rec_model = ALS.trainImplicit(ratings, rank, numIterations, alpha=0.01)

In [ ]:
rdd_recommend = ([0.75,0.,0.27615063,0.44914901,0.75690952], 1)

## >>>end